spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/NaveenKumarJadi/configuration_properties.git
          clone-on-start: true
management:
  security:
    enabled: false
