package com.naveen.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import com.mongodb.lang.NonNull;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.RequiredArgsConstructor;


@Data
@NoArgsConstructor
@AllArgsConstructor
@RequiredArgsConstructor
@Document //Maps Entity class objects to JSON formatted Documents
public class Book {

	@Id // making this variable as ID, will be auto-generated by mMongoDB
	private String id;

	@NonNull
	private Integer bookId;

	@NonNull
	private String bookName;

	@NonNull
	private String bookAuthor;

	@NonNull
	private Double bookCost;
}
