package com.naveen.db1.entity;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import com.mongodb.lang.NonNull;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.RequiredArgsConstructor;


@Data
@AllArgsConstructor
@NoArgsConstructor
@Document(collection = "USER_DETAILS") //Maps Entity class objects to JSON formatted Documents
public class User {

	@Id // making this variable as ID, will be auto-generated by mMongoDB
	private String id;

	private String username;
	private String email;
}